[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_task = "4UrP3GhXtV7o35usMeSHaacE44AnmAnjuE1xRfuVjXWx"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://black-damp-film.solana-devnet.quiknode.pro/ef65f6d74fbb607e24763eb3e128aabfeb338761/"

wallet = "./.keys/dev.json"

[scripts]
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.test.ts"
confirm_task = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/confirm_task.test.ts"
complete_task = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/complete_task.test.ts"
claim_task = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/claim_task.test.ts"
